---
title: "DESeq2 RNA frac method"
author: "Sam Haynes"
date: '2022-06-14'
output: pdf_document
---

```{r setup, include=FALSE}
library(here)
library(DESeq2)
library(tidyverse)

encode_data_files <- list.files(here("data/input/ENCODE_dataset"), full.names = TRUE)

encode_data_sets <- tibble(file = encode_data_files) %>%
  group_by(file) %>%
  summarise(read_tsv(file)) %>%
  ungroup() %>%
  transmute(sample = str_extract(file, "(?<=encode_)[a-z0-9]+(?=_)"),
            biorep = str_extract(file, "(?<=_biorep)[0-9]+(?=.tsv)"),
            gene_id,
            expected_count) %>%
  group_by(gene_id) %>%
  filter(sum(expected_count > 5) == 6)

simulated_datasets <- read_tsv(here("data/output/simulated_counts/total_sup_pel_simulated_noisy_skewed_multi_condition_counts.tsv"))

total_sup_pel_iserman_et_al_counts <- read_tsv(here("data/input/Iserman_et_al_dataset/full_transcript_counts.txt"))
```

```{r run-DESeq-simulated}
fractionation_count_matrix_simulated <- simulated_datasets %>%
  dplyr::select(-total) %>%
  pivot_longer(cols = c(pel, sup), names_to = "frac", values_to = "count")  %>%
  unite("samples",condition,rep,frac) %>%
  pivot_wider(names_from = "samples", values_from = "count") %>%
  column_to_rownames("gene_name") %>%
  as.matrix()

column_data_simulated <- data.frame(fraction = factor(rep(c("pel", "sup"), 9)),
                                condition = factor(rep(c("Random", "Marginal", "Specific"), each = 6)))

rownames(column_data_simulated) = colnames(fractionation_count_matrix_simulated)

DESeq2_data_set_simulated_random <- DESeqDataSetFromMatrix(countData = fractionation_count_matrix_simulated[,c("1_1_pel", "1_1_sup", "1_2_pel",
                                        "1_2_sup", "1_3_pel", "1_3_sup")], 
                                          colData = column_data_simulated[1:6,],
                                          design = ~fraction)

DESeq2_data_set_simulated_random <- DESeq(DESeq2_data_set_simulated_random)


DESeq2_result_simulated_random <- results(DESeq2_data_set_simulated_random)

DESeq2_data_set_simulated_marginal <- DESeqDataSetFromMatrix(countData = fractionation_count_matrix_simulated[,c("2_1_pel", "2_1_sup", "2_2_pel",
                                        "2_2_sup", "2_3_pel", "2_3_sup")], 
                                          colData = column_data_simulated[7:12,],
                                          design = ~fraction)

DESeq2_data_set_simulated_marginal <- DESeq(DESeq2_data_set_simulated_marginal)


DESeq2_result_simulated_marginal <- results(DESeq2_data_set_simulated_marginal)

DESeq2_data_set_simulated_specific <- DESeqDataSetFromMatrix(countData = fractionation_count_matrix_simulated[,c("3_1_pel", "3_1_sup", "3_2_pel",
                                        "3_2_sup", "3_3_pel", "3_3_sup")], 
                                          colData = column_data_simulated[13:18,],
                                          design = ~fraction)

DESeq2_data_set_simulated_specific <- DESeq(DESeq2_data_set_simulated_specific)


DESeq2_result_simulated_specific <- results(DESeq2_data_set_simulated_specific)
```

```{r run-DESeq-encode}
fractionation_count_matrix_encode <- encode_data_sets %>%
  ungroup() %>%
  filter(sample != "total") %>%
  unite("samples",sample,biorep) %>%
  mutate(expected_count = as.integer(expected_count)) %>%
  pivot_wider(names_from = "samples", values_from = "expected_count")  %>%
  column_to_rownames("gene_id") %>%
  as.matrix()

column_data_encode <- data.frame(fraction = factor(rep(c("cytoplasm", "nuclear"), each = 2)))

rownames(column_data_encode) = colnames(fractionation_count_matrix_encode)

DESeq2_data_set_encode <- DESeqDataSetFromMatrix(countData = fractionation_count_matrix_encode, 
                                          colData = column_data_encode,
                                          design = ~fraction)

DESeq2_data_set_encode <- DESeq(DESeq2_data_set_encode)


DESeq2_result_encode <- results(DESeq2_data_set_encode)
```

```{r run-DESeq-iserman}
fractionation_count_matrix_iserman_WT_30C <- total_sup_pel_iserman_et_al_counts %>%
  dplyr::select("ensembl_gene_id", "WT_30C_1_pellet_250", "WT_30C_2_pellet_251",
         "WT_30C_1_SN_232","WT_30C_2_SN_233") %>%
  column_to_rownames("ensembl_gene_id") %>%
  as.matrix()

column_data_iserman_WT_30C <- data.frame(fraction = factor(rep(c("pel", "sup"), each = 2)))

rownames(column_data_iserman_WT_30C) <- colnames(fractionation_count_matrix_iserman_WT_30C)

fractionation_count_matrix_iserman_WT_40C <- total_sup_pel_iserman_et_al_counts %>%
  dplyr::select("ensembl_gene_id", "WT_40C_1_pellet_252",
                "WT_40C_2_pellet_253", "WT_40C_1_SN_234", "WT_40C_2_SN_235") %>%
  column_to_rownames("ensembl_gene_id") %>%
  as.matrix()

column_data_iserman_WT_40C <- data.frame(fraction = factor(rep(c("pel", "sup"), each = 2)))

rownames(column_data_iserman_WT_40C) <- colnames(fractionation_count_matrix_iserman_WT_40C)

fractionation_count_matrix_iserman_WT_42C <- total_sup_pel_iserman_et_al_counts %>%
  dplyr::select("ensembl_gene_id", "WT_42C_1_pellet_254",
                "WT_42C_2_pellet_255", "WT_42C_1_SN_236", "WT_42C_2_SN_237") %>%
  column_to_rownames("ensembl_gene_id") %>%
  as.matrix()

column_data_iserman_WT_42C <- data.frame(fraction = factor(rep(c("pel", "sup"), each = 2)))

rownames(column_data_iserman_WT_42C) <- colnames(fractionation_count_matrix_iserman_WT_42C)

DESeq2_data_set_iserman_WT_30C <- DESeqDataSetFromMatrix(countData = fractionation_count_matrix_iserman_WT_30C, 
                                          colData = column_data_iserman_WT_30C,
                                          design = ~fraction)

DESeq2_data_set_iserman_WT_30C <- DESeq(DESeq2_data_set_iserman_WT_30C)


DESeq2_result_iserman_WT_30C <- results(DESeq2_data_set_iserman_WT_30C)

DESeq2_data_set_iserman_WT_40C <- DESeqDataSetFromMatrix(countData = fractionation_count_matrix_iserman_WT_40C, 
                                          colData = column_data_iserman_WT_40C,
                                          design = ~fraction)

DESeq2_data_set_iserman_WT_40C <- DESeq(DESeq2_data_set_iserman_WT_40C)


DESeq2_result_iserman_WT_40C <- results(DESeq2_data_set_iserman_WT_40C)

DESeq2_data_set_iserman_WT_42C <- DESeqDataSetFromMatrix(countData = fractionation_count_matrix_iserman_WT_42C, 
                                          colData = column_data_iserman_WT_42C,
                                          design = ~fraction)

DESeq2_data_set_iserman_WT_42C <- DESeq(DESeq2_data_set_iserman_WT_42C)


DESeq2_result_iserman_WT_42C <- results(DESeq2_data_set_iserman_WT_42C)

```

```{r save-result, eval=FALSE}
write_tsv(DESeq2_result_simulated_specific %>%
            as.data.frame() %>%
            rownames_to_column(var = "gene_name") %>%
            dplyr::select(gene_name, baseMean, log2FoldChange, padj) %>%
            mutate(condition = "specific") %>%
            bind_rows(DESeq2_result_simulated_random %>%
                        as.data.frame() %>%
                        rownames_to_column(var = "gene_name") %>%
                        dplyr::select(gene_name, baseMean, log2FoldChange, padj) %>%
                        mutate(condition = "random")) %>%
            bind_rows(DESeq2_result_simulated_marginal %>%
                        as.data.frame() %>%
                        rownames_to_column(var = "gene_name") %>%
                        dplyr::select(gene_name,baseMean, log2FoldChange, padj) %>%
                        mutate(condition = "marginal")),
          here("./data/output/diff_frac_models/DESeq2_simulated_counts.tsv"))

write_tsv(DESeq2_result_encode %>%
            as.data.frame() %>%
            rownames_to_column(var = "gene_name") %>%
            dplyr::select(gene_name, baseMean, log2FoldChange, padj),
          here("./data/output/diff_frac_models/DESeq2_encode_counts.tsv"))

write_tsv(DESeq2_result_iserman_WT_42C %>%
            as.data.frame() %>%
            rownames_to_column(var = "gene_name") %>%
            dplyr::select(gene_name, baseMean, log2FoldChange, padj) %>%
            mutate(condition = "WT_42C") %>%
            bind_rows(DESeq2_result_iserman_WT_40C %>%
                        as.data.frame() %>%
                        rownames_to_column(var = "gene_name") %>%
                        dplyr::select(gene_name, baseMean, log2FoldChange, padj)%>%
                        mutate(condition = "WT_40C")) %>%
            bind_rows(DESeq2_result_iserman_WT_30C %>%
                        as.data.frame() %>%
                        rownames_to_column(var = "gene_name") %>%
                        dplyr::select(gene_name, baseMean, log2FoldChange, padj) %>%
                        mutate(condition = "WT_30C")),
          here("./data/output/diff_frac_models/DESeq2_iserman_counts.tsv"))
```
