---
title: "Edward's Frac Model"
author: "Sam Haynes"
date: '2022-06-09'
output: html_document
---

```{r setup, include=false}
library(rstan)
library(DESeq2)
library(tidyverse)
library(here)
library(tidybayes)

total_sup_pel_iserman_et_al_counts <- read_tsv(here("data/input/Iserman_et_al_dataset/full_transcript_counts.txt")) %>%
  pivot_longer(-ensembl_gene_id, names_to = "sample", values_to = "counts") %>%
  separate(sample, "_", into = c("strain", "temperature", "rep", "fraction", NA))
```

```{r mixingratiosTSP_stan}

mdat_mixingTSP <- function(ctdata) {
  ctdata = ctdata %>% arrange(gene_name, rep, condition)
  NRNA=length(unique(ctdata$gene_name))
  NREP=length(unique(ctdata$rep))
  NCON=length(unique(ctdata$condition))
    ## make data for stan fit
    head(ctdata)
    list(NRNA=NRNA,
         NREP=NREP,
         NCON=NCON,
         tot_obs=array(as.integer(round(ctdata$total)), c(NRNA, NREP, NCON)),
         sup_obs=array(as.integer(round(ctdata$sup)), c(NRNA, NREP, NCON)),
         p100_obs=array(as.integer(round(ctdata$pel)), c(NRNA, NREP, NCON))
         )
    
}

make_mixingTSP <- function(ctdata) {
    stan_dat <- mdat_mixingTSP(ctdata)
    stan(model_code='// -*- mode: C -*-
data {
  // Number of RNAs
  int<lower=1> NRNA;
  
  // Number of replicates
  int<lower=1> NREP;
  
  // Number of conditions
  int<lower=1> NCON;
  
  // Note: These are all integers
  // columns t, s, p
  int<lower=0> tot_obs[NRNA, NREP, NCON];
  int<lower=0> sup_obs[NRNA, NREP, NCON];
  int<lower=0> p100_obs[NRNA, NREP, NCON];
}
parameters {
  // Unnormalized mixing proportions
  // real<lower=0> mixing_t[NREP, NCON];
  real<lower=0> mixing_sup[NREP, NCON];
  real<lower=0> mixing_p100[NREP, NCON];
  
  // dispersion parameter for counts
  real phi;
}
model{
  // Cauchy prior for negbin dispersion parameter
  phi ~ cauchy(0,3);
    
  for(con in 1:NCON){
    // mixing ratios
    mixing_sup[, con] ~ gamma(1,1);
    mixing_p100[, con] ~ gamma(1,1);
  
    for(rna in 1:NRNA){ 
      for(rep in 1:NREP){
        // count distn negative binomial with specified means
        // Total
        tot_obs[rna, rep, con] ~ neg_binomial_2(mixing_sup[rep, con] * sup_obs[rna, rep, con] + mixing_p100[rep, con] * p100_obs[rna, rep, con], phi);
      }
    }
  }
}
generated quantities{
  // print("Mixing pars (sup,p100) = (", mixing_sup,",",mixing_p100,")");
  // print("dispersion phi = ", phi);
  // print("------------------");
}
',
data=stan_dat,chains = 1,iter = 10)
}

fit_mixingTSP <- function(ctdata,stan_mixing=NULL,...) {
    stan_dat <- mdat_mixingTSP(ctdata)
    if (is.null(stan_mixing)) {
        stan_mixing <- make_mixingTSP(ctdata)
    }
    stan_mixing_fit <- stan(fit=stan_mixing,data=stan_dat,chains = 4,...)
    return(stan_mixing_fit)
}

getmixingratiosTSP <- function(ctdata,iter=1000,
                                control=list(adapt_delta=0.85),...) {
    # head(ctdata) %>% print()
    stan_model <- fit_mixingTSP(ctdata=ctdata,iter=iter,control=control,...)
    
    # return medians
    list(
      mixing_factors = stan_model %>% 
          spread_draws(mixing_p100[rep, condition],
                       mixing_sup[rep, condition]) %>%
          summarise_draws(),
      phi = stan_model %>% 
          spread_draws(phi) %>%
          summarise_draws(),
      lp = stan_model %>% 
          spread_draws(lp__) %>%
          summarise_draws())
}

```

```{r run-stan-model-on-sim-data}

# compile stan model, test it with 10 iterations, save output
stan_count_model <- total_sup_pel_simulated_noisy_counts %>%
  filter(total > 5,
         sup > 5,
         pel > 5) %>%
    make_mixingTSP()

# Specify a seed for random number generator so output is reproducible
myseed = 39

# run stan mixing ratio inference, reusing same model
mixing_ratios_TSP <- total_sup_pel_simulated_noisy_counts %>%
  filter(total > 5,
         sup > 5,
         pel > 5) %>%
    getmixingratiosTSP(stan_mixing=stan_count_model,iter=1000,seed=myseed)

```

```{r run-DESeq2-with-scale-factors}

fractionation_count_matrix_1_2 <- total_sup_pel_simulated_noisy_counts %>%
  filter(condition != 3) %>%
  dplyr::select(-total) %>%
  pivot_wider(names_from = c("rep", "condition"),
              values_from = c("sup", "pel")) %>%
  column_to_rownames("gene_name") %>%
  as.matrix()

column_data_1_2 <- data.frame(fraction = factor(rep(c("sup", "pel"), each = 6)),
                          condition = factor(rep(rep(1:2,each = 3),2)))

rownames(column_data_1_2) <- colnames(fractionation_count_matrix_1_2)

DESeq2_data_set_1_2 <- DESeqDataSetFromMatrix(countData = fractionation_count_matrix_1_2, 
                                          colData = column_data_1_2,
                                          design = ~fraction * condition)



fractionation_count_matrix_2_3 <- total_sup_pel_simulated_noisy_counts %>%
  filter(condition != 1) %>%
  dplyr::select(-total) %>%
  pivot_wider(names_from = c("rep", "condition"),
              values_from = c("sup", "pel")) %>%
  column_to_rownames("gene_name") %>%
  as.matrix()

column_data_2_3 <- data.frame(fraction = factor(rep(c("sup", "pel"), each = 6)),
                          condition = factor(rep(rep(2:3,each = 3),2)))

rownames(column_data_2_3) <- colnames(fractionation_count_matrix_2_3)

DESeq2_data_set_2_3 <- DESeqDataSetFromMatrix(countData = fractionation_count_matrix_2_3, 
                                          colData = column_data_2_3,
                                          design = ~fraction * condition)

fractionation_count_matrix_1_3 <- total_sup_pel_simulated_noisy_counts %>%
  filter(condition != 2) %>%
  dplyr::select(-total) %>%
  pivot_wider(names_from = c("rep", "condition"),
              values_from = c("sup", "pel")) %>%
  column_to_rownames("gene_name") %>%
  as.matrix()

column_data_1_3 <- data.frame(fraction = factor(rep(c("sup", "pel"), each = 6)),
                          condition = factor(rep(rep(c(1,3),each = 3),2)))

rownames(column_data_1_3) <- colnames(fractionation_count_matrix_1_3)

DESeq2_data_set_1_3 <- DESeqDataSetFromMatrix(countData = fractionation_count_matrix_1_3, 
                                          colData = column_data_1_3,
                                          design = ~fraction * condition)


sizeFactors(DESeq2_data_set_1_2) <- mixing_ratios_TSP$mixing_factors %>% 
  dplyr::select(rep, condition, variable, median) %>% 
  mutate(variable = str_remove(variable, "mixing_"), variable = str_replace(variable, "p100", "pel")) %>% 
  filter(condition %in% c(1,2)) %>%
  arrange(desc(variable), condition, rep) %>%
  pivot_wider(names_from = c("variable", "rep", "condition"), values_from = "median") %>%
  as_vector()

sizeFactors(DESeq2_data_set_1_3) <- mixing_ratios_TSP$mixing_factors %>% 
  dplyr::select(rep, condition, variable, median) %>% 
  mutate(variable = str_remove(variable, "mixing_"), variable = str_replace(variable, "p100", "pel")) %>% 
  filter(condition %in% c(1,3)) %>%
  arrange(desc(variable), condition, rep) %>%
  pivot_wider(names_from = c("variable", "rep", "condition"), values_from = "median") %>%
  as_vector()

sizeFactors(DESeq2_data_set_2_3) <- mixing_ratios_TSP$mixing_factors %>% 
  dplyr::select(rep, condition, variable, median) %>% 
  mutate(variable = str_remove(variable, "mixing_"), variable = str_replace(variable, "p100", "pel")) %>% 
  filter(condition %in% c(2,3)) %>%
  arrange(desc(variable), condition, rep) %>%
  pivot_wider(names_from = c("variable", "rep", "condition"), values_from = "median") %>%
  as_vector()

DESeq2_data_set_1_3 <- DESeq(DESeq2_data_set_1_3, test = "LRT", reduced = ~fraction + condition)


DESeq2_result_1_3 <- results(DESeq2_data_set_1_3)

DESeq2_data_set_2_3 <- DESeq(DESeq2_data_set_2_3, test = "LRT", reduced = ~fraction + condition)


DESeq2_result_2_3 <- results(DESeq2_data_set_2_3)

DESeq2_data_set_1_2 <- DESeq(DESeq2_data_set_1_2, test = "LRT", reduced = ~fraction + condition)


DESeq2_result_1_2 <- results(DESeq2_data_set_1_2)

DESeq2_with_edward_model_results <- results(DESeq2_data_set_1_2, name = "fractionsup.condition2") %>%
              as.tibble(rownames = "gene_name") %>%
              dplyr::select(gene_name, baseMean, log2FoldChange, pvalue) %>%
              mutate("condition_A" = 2, "condition_B" = 1) %>%
  bind_rows(results(DESeq2_data_set_1_3, name = "fractionsup.condition3") %>%
              as.tibble(rownames = "gene_name") %>%
              dplyr::select(gene_name, baseMean, log2FoldChange, pvalue) %>%
              mutate("condition_A" = 3, "condition_B" = 1))%>%
  bind_rows(results(DESeq2_data_set_2_3, name = "fractionsup.condition3") %>%
              as.tibble(rownames = "gene_name") %>%
              dplyr::select(gene_name, baseMean, log2FoldChange, pvalue) %>%
              mutate("condition_A" = 3, "condition_B" = 2))

```

```{r output_results}
write_tsv(DESeq2_with_edward_model_results, here("data/output/diff_frac_models/DESeq2_with_edward_model_results.tsv"))
```