---
title: "Exploring fractionation datasets"
author: "Sam Haynes"
date: '2022-11-08'
output: html_document
---

```{r setup, include=FALSE}
library(here)
library(tidyverse)
library(latex2exp)
library(cowplot)

mytheme <- gridExtra::ttheme_default(
  core = list(padding = unit(c(2.5, 2.5), "mm")))

theme_set(
  theme_cowplot(font_size = 12, 
                font_family = "sans",
                rel_small = 10/12,
                rel_tiny = 9/12,
                rel_large = 12/12) %+replace%
    theme(legend.position = "bottom",
          legend.justification = "center"))

knitr::opts_chunk$set(echo = FALSE)

encode_data_files <- list.files(here("data/input/ENCODE_dataset"), full.names = TRUE)

encode_data_sets <- tibble(file = encode_data_files) %>%
  group_by(file) %>%
  summarise(read_tsv(file)) %>%
  ungroup() %>%
  transmute(sample = str_extract(file, "(?<=encode_)[a-z0-9]+(?=_)"),
            biorep = str_extract(file, "(?<=_biorep)[0-9]+(?=.tsv)"),
            gene_id,
            expected_count) %>%
  group_by(gene_id) %>%
  filter(sum(expected_count > 5) == 6)

yeast_stress_datasets <- read_tsv(here("data/input/Iserman_et_al_dataset/full_transcript_counts.txt")) %>%
  pivot_longer(-ensembl_gene_id, names_to = "sample", values_to = "counts") %>%
  group_by(ensembl_gene_id) %>%
  filter(sum(counts > 5) == 36) %>%
  transmute(gene_id = ensembl_gene_id,
            strain = str_extract(sample, "^[A-Z]+"),
            temp = str_extract(sample, "[0-9]+C"),
            biorep = str_extract(sample, "(?<=_)[12](?=_)"),
            frac = str_extract(sample, "(SN|pellet|total)"),
            counts)

simulated_datasets <- read_tsv(here("data/output/simulated_counts/total_sup_pel_simulated_noisy_skewed_multi_condition_counts.tsv"))

```

```{r rep-correlation-plot}

encode_fraction_dictionary <- tibble(sample = c("cytoplasm", "nuclear", "total"),
                                     pretty_name = c("Cytoplasm", "Nucleus", "Total"))

encode_pearson_cor <- encode_data_sets  %>%
  pivot_wider(names_from = biorep, 
              values_from = expected_count) %>% 
  group_by(sample) %>%
  summarise(cor = cor(`1`, `2`),
            r_cor_label = paste(TeX(paste0("R = ", signif(cor,digits = 3))))) %>%
  inner_join(encode_fraction_dictionary)

encode_replicate_quality <- ggplot(encode_data_sets %>%
                                     inner_join(encode_fraction_dictionary) %>%
                                     pivot_wider(names_from = biorep, 
                                                 values_from = expected_count)) +
  geom_point(aes(x = `1`, y =`2`)) +
  facet_wrap(~pretty_name) +
  scale_x_log10(labels = scales::label_log(), breaks = c(100, 10000, 1000000)) +
  scale_y_log10(labels = scales::label_log(), breaks = c(100, 10000, 1000000)) +
  coord_equal() +
  labs(x = "Biorep 1", y = "Biorep 2") + 
  geom_text(aes(label = r_cor_label), 
            data = encode_pearson_cor, 
            x = 4.8, y = 6, hjust = 1, vjust = 0)

yeast_stress_fraction_dictionary <- tibble(frac = c("pellet", "SN", "total"),
                                     pretty_name = c("Pellet", "Supernatent", "Total"))

yeast_stress_pearson_cor <- yeast_stress_datasets %>%
  filter(strain == "WT") %>% 
  pivot_wider(names_from = biorep,
              values_from = counts) %>% 
  group_by(frac) %>%
  summarise(cor = cor(`1`, `2`),
            r_cor_label = paste(TeX(paste0("R = ", signif(cor,digits = 3))))) %>%
  inner_join(yeast_stress_fraction_dictionary)

yeast_stress_replicate_quality <- ggplot(yeast_stress_datasets %>%
                                           inner_join(yeast_stress_fraction_dictionary) %>%
                                           filter(strain == "WT") %>% 
                                           pivot_wider(names_from = biorep,
                                                       values_from = counts)) +
  geom_point(aes(x = `1`, y =`2`, colour = temp)) +
  facet_wrap(~pretty_name) +
  scale_x_log10(labels = scales::label_log(), breaks = c(100, 10000, 1000000)) +
  scale_y_log10(labels = scales::label_log(), breaks = c(100, 10000, 1000000)) +
  coord_equal() +
  labs(x = "Biorep 1", y = "Biorep 2", colour = "Condition") +
  geom_text(aes(label = r_cor_label), 
            data = yeast_stress_pearson_cor, 
            x = 3.9, y = 5, hjust = 1, vjust = 0)

simulated_fraction_dictionary <- tibble(condition = c(1, 2, 3),
                                     pretty_name = factor(c("Random", "Marginally Biased Fractionation",
                                                            "Specific Fractionation"),
                                                          levels = c("Random", "Marginally Biased Fractionation",
                                                            "Specific Fractionation")))

simulated_dataset_comparison <- ggplot(simulated_datasets %>%
         inner_join(simulated_fraction_dictionary)) +
  geom_point(aes(x = pel, y = sup), alpha = 0.4) +
  facet_wrap(~pretty_name, nrow=1) + 
  scale_y_log10(labels = scales::label_log(), breaks = c(1, 100, 10000)) + 
  scale_x_log10(labels = scales::label_log(), breaks = c(1, 100, 10000)) +
  labs(x = "Fraction A", y ="Fraction B") +
  geom_abline(intercept = 0, slope = 1, colour = "grey") +
  coord_equal()

dataset_summary_plot <- plot_grid(simulated_dataset_comparison,
                                  encode_replicate_quality,
                                  yeast_stress_replicate_quality,
                                  ncol = 1,
                                  labels = c("A", "B", "C"),
                                  rel_heights = c(1,0.9,1.1))

```
```{r output-graph, eval=FALSE}
ggsave2(here("data/output/figures/fractionation_dataset_summary.png"), 
        dataset_summary_plot, dpi = 300, width = 185, height= 240, units = "mm")
```
