---
title: "Guido's model"
author: "Sam Haynes"
date: '2022-06-09'
output: html_document
---

```{r setup, include=FALSE}
library(rstan)
library(tidyverse)
library(here)
library(tidybayes)

options(mc.cores = parallel::detectCores())

simulated_datasets <- read_tsv(here("data/output/simulated_counts/total_sup_pel_simulated_noisy_skewed_multi_condition_counts.tsv"))

encode_subsample_dataset <- read_tsv(here("data/output/subsampled_experimental_counts/ENCODE_dataset_subsampled.tsv"))

encode_full_dataset <- read_tsv(here("data/input/ENCODE_dataset/ENCODE_dataset_bayesian_combined.tsv"))

total_sup_pel_iserman_et_al_counts <- read_tsv(here("data/input/Iserman_et_al_dataset/full_transcript_counts.txt")) %>%
  pivot_longer(-ensembl_gene_id, names_to = "sample", values_to = "counts") %>%
  separate(sample, "_", into = c("strain", "temperature", "rep", "fraction", NA)) %>%
  pivot_wider(names_from = fraction, values_from = counts) %>%
  transmute(gene_name = ensembl_gene_id,
            condition = paste0(strain, "_", temperature),
            pel = pellet,
            sup = SN,
            rep,
            total) %>%
  filter(condition %in% c("WT_30C", "WT_40C", "WT_42C")) %>%
  filter(pel > 0 | sup > 0 | total > 0) %>%
  group_by(gene_name) %>%
  filter(length(gene_name) == 6) %>%
  ungroup()


#total_sup_pel_iserman_et_al_counts_subsample <- read_tsv(here("data/output/simulated_counts/total_sup_pel_iserman_et_al_counts_subsample.tsv"))

#total_sup_pel_simulated_noisy_counts <- read_tsv(here("data/output/simulated_counts/total_sup_pel_simulated_noisy_skewed_multi_condition_counts.tsv"))
```

```{r mixingratiosTSP_stan}
mdat_mixingTSP <- function(ctdata) {
  # fix order of counts so grouped together by replicate
  ctdata = ctdata %>%
    arrange(gene_name, rep, condition)
  
  # define total rep and RNA
  NRNA=length(unique(ctdata$gene_name))
  NREP=length(unique(ctdata$rep))
  NCON=length(unique(ctdata$condition))
  
    ## make data for stan fit
    list(NRNA=NRNA,
         NREP=NREP,
         NCON=NCON,
         tot_obs=array(as.integer(round(ctdata$total)), c(NCON, NREP, NRNA)),
         sup_obs=array(as.integer(round(ctdata$sup)), c(NCON, NREP, NRNA)),
         pel_obs=array(as.integer(round(ctdata$pel)), c(NCON, NREP, NRNA))
         )
    
}

make_mixingTSP <- function(ctdata) {
    stan_dat <- mdat_mixingTSP(ctdata)
    stan(model_code='// -*- mode: C -*-
data {
  // Number of RNAs
  int<lower=1> NRNA; 
  
  // Number of replicates
  int<lower=1> NREP; 
  
  // Number of conditions
  int<lower=1> NCON;
  
  // Note: These are all integers
  // columns t, s, p
  int<lower=0> tot_obs[NCON, NREP, NRNA];
  int<lower=0> sup_obs[NCON, NREP, NRNA];
  int<lower=0> pel_obs[NCON, NREP, NRNA];
}
parameters {
  // Normalising factors
  real scale_factor_mean;
  real<lower=0> tot_scale_factor[NCON, NREP];
  real sup_scale_factor[NCON, NREP];
  real pel_scale_factor[NCON, NREP];

  // latent counts
  vector[NRNA] gene_count_condition[NCON];
  vector[NRNA] pel_count_condition[NCON];
  
  // latent count prior parameters
  real norm_alpha;
  real<lower=0> norm_beta;
  
  // dispersion parameter for counts
  real<lower=0> phi[3];
}

transformed parameters{
// latent counts
  vector[NRNA] sup_latent[NCON];
  vector[NRNA] pel_latent[NCON];

  for(con in 1:NCON){
    sup_latent[con] = gene_count_condition[con];

    pel_latent[con] = sup_latent[con] + pel_count_condition[con];
  }
}

model{

norm_alpha ~ normal(7,2);
norm_beta ~ normal(2,1);

for(con in 1:NCON){

    scale_factor_mean ~ normal(0, 0.5);
    tot_scale_factor[con] ~ normal(10, 0.1);
    pel_scale_factor[con] ~ normal(scale_factor_mean, 0.1);
    sup_scale_factor[con] ~ normal(scale_factor_mean, 0.1);
   
    phi ~ normal(100, 10);

    // latent counts
    gene_count_condition[con] ~ normal(norm_alpha, norm_beta);
    pel_count_condition[con] ~ normal(0, 1);
    

    for(rep in 1:NREP){
          // fractions
          sup_obs[con, rep] ~ neg_binomial_2_log(sup_scale_factor[con, rep] + sup_latent[con],
                                                phi[2]);
                                              
        pel_obs[con, rep] ~ neg_binomial_2_log(pel_scale_factor[con, rep] + pel_latent[con],
                                                phi[3]);

        // count distn negative binomial with specified means
        // total
        tot_obs[con, rep] ~ neg_binomial_2(tot_scale_factor[con, rep] * (exp(pel_latent[con]) + exp(sup_latent[con])),
					 	phi[1]);
      }
  }
}
generated quantities{
	vector[NRNA] temp_sum;
        real<lower=0> sup_obs_sim[NCON, NRNA];
        real<lower=0> pel_obs_sim[NCON, NRNA];
	real<lower=0> tot_obs_sim[NCON, NRNA]; 
	for(con in 1:NCON){
		sup_obs_sim[con] = neg_binomial_2_log_rng(sup_scale_factor[con, 2] + sup_latent[con],
                                                phi[2]);

        	pel_obs_sim[con] = neg_binomial_2_log_rng(pel_scale_factor[con, 2] + pel_latent[con],
                                                phi[3]);

		temp_sum = exp(pel_latent[con]) + exp(sup_latent[con]);

		tot_obs_sim[con] = neg_binomial_2_rng(tot_scale_factor[con, 1] * temp_sum,
						phi[1]);
	}
}',
data=stan_dat,chains = 1,iter = 10)
}

fit_mixingTSP <- function(ctdata,stan_mixing=NULL,...) {
    stan_dat <- mdat_mixingTSP(ctdata)
    if (is.null(stan_mixing)) {
        stan_mixing <- make_mixingTSP(ctdata)
    }
    stan_mixing_fit <- stan(fit=stan_mixing,data=stan_dat,chains = 4,...)
    return(stan_mixing_fit)
}

extract_summary_statistics <- function(stan_model){
    # return medians
    list(
        latent_counts = stan_model %>% 
          spread_draws(sup_latent[condition, gene_name],
                       pel_latent[condition, gene_name]) %>%
          summarise_draws(),
        scale_factors = stan_model %>% 
          spread_draws(tot_scale_factor[condition, rep],
                       sup_scale_factor[condition, rep],
                       pel_scale_factor[condition, rep]) %>%
          summarise_draws(),
        prior_parameters = stan_model %>% 
          spread_draws(lognorm_alpha[condition, fraction],
                       lognorm_beta[condition, fraction]) %>%
          summarise_draws(),
	dispersion = stan_model %>%
          spread_draws(phi[condition, fraction]) %>%
          summarise_draws(),
        lp = stan_model %>% 
          spread_draws(lp__) %>%
          summarise_draws())
}

getmixingratiosTSP <- function(ctdata,iter=1000,
                                control=list(adapt_delta=0.85),...) {
    # head(ctdata) %>% print()
    stan_model <- fit_mixingTSP(ctdata=ctdata,iter=iter,control=control,...)
    
    extract_summary_statistics(stan_model)
}

test_frac_across_condition <- function(condition, ratio){
  unique_permutations <- tibble(condition_A = unique(condition), condition_B = unique(condition)) %>% 
    expand(condition_A, condition_B) %>% 
    filter(condition_A > condition_B)
  
  unique_permutations %>%
    dplyr::select(condition_A) %>%
    inner_join(tibble(condition_A = condition, ratio_A = ratio), by = "condition_A") %>%
    bind_cols(unique_permutations %>%
                dplyr::select(condition_B) %>%
                inner_join(tibble(condition_B = condition, ratio_B = ratio), by = "condition_B")) %>%
    group_by(condition_A, condition_B) %>%
    summarise(p.value = sum(ratio_A > ratio_B) / (length(ratio)/ length(unique(condition))), .groups = "drop")
}

one_condition_extract <- function(stanmodel){
stanmodel %>%                                      
          spread_draws(sup_latent[condition, gene_name],
                       pel_latent[condition, gene_name]) %>% summarise_draws() %>% ungroup() %>% dplyr::select(gene_name,variable,median)%>%pivot_wider(names_from="variable",values_from="median") %>% inner_join(stanmodel %>% 
          spread_draws(sup_latent[condition, gene_name],
                       pel_latent[condition, gene_name]) %>% group_by(gene_name) %>% summarise(pvalue = sum(sup_latent < pel_latent) / 2000) %>% ungroup())
}

test_diff_condition <- function(stan_model){
  gene_count_samples <- stan_model %>% 
          spread_draws(gene_count_condition[condition, gene_name])
  
  pel_count_samples <- stan_model %>% 
          spread_draws(pel_count_condition[condition, gene_name])
  
  summary_stats_ratio <- gene_count_samples %>%
          summarise_draws() %>% 
    transmute(gene_name, condition, gene_count_condition = median) %>%
    inner_join(pel_count_samples %>%
                 summarise_draws() %>% 
                 transmute(gene_name, condition, pel_count_condition = median)) 
  
  
  pel_count_samples %>%
    group_by(gene_name, condition) %>%
    transmute(pel_count_condition = sample(pel_count_condition)) %>%
    ungroup() %>%
    group_by(gene_name) %>%
    summarise(test_frac_across_condition(condition, pel_count_condition), .groups = "drop")  %>% 
    rename(p.value_frac=p.value) %>%
    inner_join(gene_count_samples %>%
                 group_by(gene_name, condition) %>%
                 transmute(gene_count_condition = sample(gene_count_condition)) %>%
                 ungroup() %>%
                 group_by(gene_name) %>%
                 summarise(test_frac_across_condition(condition, gene_count_condition), 
                           .groups = "drop")  %>% 
                 rename(p.value_total=p.value)) %>%
    inner_join(summary_stats_ratio, by = c("gene_name"="gene_name", "condition_A" = "condition")) %>%
    rename(pel_count_condition_A = pel_count_condition, 
           gene_count_condition_A = gene_count_condition) %>%
    inner_join(summary_stats_ratio, by = c("gene_name"="gene_name", "condition_B" = "condition")) %>%
    rename(pel_count_condition_B = pel_count_condition, 
           gene_count_condition_B = gene_count_condition)
}

```

```{r run-stan-model-on-sim-data, eval=FALSE}

# compile stan model, test it with 10 iterations, save output
stan_count_model <- total_sup_pel_iserman_et_al_counts %>%
  filter(total > 5,
         sup > 5,
         pel > 5) %>%
    make_mixingTSP()

# Specify a seed for random number generator so output is reproducible
myseed = 39

# run stan mixing ratio inference, reusing same model
mixing_ratios_TSP <- total_sup_pel_simulated_noisy_counts %>%
    getmixingratiosTSP(, stan_mixing=stan_count_model,iter=500,seed=myseed)

mixing_ratios_TSP <- total_sup_pel_iserman_et_al_counts %>%
    getmixingratiosTSP(, stan_mixing=stan_count_model,iter=20,seed=myseed)

stan_count_model <- total_sup_pel_simulated_noisy_counts %>%
    fit_mixingTSP(stan_mixing=stan_count_model, iter=100)

summary_stats <- extract_summary_statistics(stan_count_model)

compare_ratio <- summary_stats$latent_counts %>%
  select(gene_name, variable, median) %>%
  pivot_wider(names_from = variable, values_from = median) %>%
  mutate(ratio = sup_latent / pel_latent) %>%
  filter(ratio < 4)

shinystan::launch_shinystan(stan_count_model)

```

```{r output_results, eval=FALSE}
write_tsv(mixing_ratios_TSP, here("data/output/stan_model/mixing_ratios_TSP_latent.tsv"))
```



