---
title: "Simulated Fractionation Dataset"
author: "Sam Haynes"
date: '2022-06-08'
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(MASS)
library(here)

num_gene = 300
phi = 100
num_rep = 3
num_condition = 3
noisy_neg_bin_dispersion = 20

knitr::opts_chunk$set(echo = FALSE)

thirty_degree_total_rna_count <- read_tsv(here("./data/input/DAD-80.txt"),
                                          col_names = c("gene_name",
                                                        "count")) %>%
  mutate(count = as.integer(count), src = "exp") %>%
  filter(count > 0)

thirty_degree_sup_rna_count <- read_tsv(here("./data/input/DAD-81.txt"),
                                          col_names = c("gene_name",
                                                        "count")) %>%
  mutate(count = as.integer(count), src = "exp") %>%
  filter(count > 0)

thirty_degree_pel_rna_count <- read_tsv(here("./data/input/DAD-82.txt"),
                                          col_names = c("gene_name",
                                                        "count")) %>%
  mutate(count = as.integer(count), src = "exp") %>%
  filter(count > 0)
```

```{r fit-lnorm-rna-count-model}
set.seed(333)
total_count_model <- fitdistr(thirty_degree_total_rna_count$count,"lognormal")

simulate_total_rna_count <- tibble(gene_name = as.character(1:length(thirty_degree_total_rna_count$gene_name)), 
                                   count = rlnorm(length(gene_name),
                                                  meanlog = total_count_model$estimate[1], 
                                                  sdlog = total_count_model$estimate[2]),
                                   src = "sim")

ggplot(thirty_degree_total_rna_count %>%
         bind_rows(simulate_total_rna_count)) +
  geom_histogram(aes(x = log(count),
                   fill = src),
               alpha = 0.7,
               bins = 60,
               position = "identity") +
  theme_light() +
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "ln(RNA count)", y = "", title = "Simulated vs Experimental Total RNA counts")


```

```{r balanced-simulated-frac-counts}
set.seed(338)
sample_noisy_counts <- function(mean, dispersion, rep_scale_factor){
  rnbinom(length(mean),
          size = dispersion,
          mu  = mean * rep_scale_factor)
}

sup_pel_simulated_fractions <- tibble(gene_name = 1:num_gene,
                                      sup_frac = c(rep(0.5, num_gene/2),
                                                   rep(0.75,num_gene/4),
                                                   rep(0.25,num_gene/4)),
                                      pel_frac = 1 - sup_frac)

tot_sup_pel_scale_factor <- tibble(rep = 1:num_rep,
                                   total = runif(num_rep, min = 0.5, max = 3),
                                   sup = runif(num_rep, min = 0.5, max = 3),
                                   pel = runif(num_rep, min = 0.5, max = 3))

total_sup_pel_simulated_mean_counts <- tibble(gene_name = 1:length(sup_pel_simulated_fractions$sup_frac),
                                              total = rlnorm(length(gene_name),
                                                  meanlog = total_count_model$estimate[1], 
                                                  sdlog = total_count_model$estimate[2]),
                                              sup = total * sup_pel_simulated_fractions$sup_frac,
                                              pel = total * sup_pel_simulated_fractions$pel_frac)

total_sup_pel_simulated_noisy_counts <- total_sup_pel_simulated_mean_counts %>%
  pivot_longer(c("total", "sup", "pel"),
               names_to = "fraction",
               values_to = "perfect_counts") %>%
   inner_join(tot_sup_pel_scale_factor %>%
                pivot_longer(c("total", "sup", "pel"),
                             names_to = "fraction",
                             values_to = "scale_factor")) %>%
  group_by(fraction, rep) %>%
  summarise(gene_name = gene_name,
            noisy_counts = sample_noisy_counts(perfect_counts, phi, scale_factor)) %>%
  pivot_wider(names_from = "fraction",
              values_from = "noisy_counts") %>%
  mutate(total = as.integer(total),
         sup = as.integer(sup),
         pel = as.integer(pel)) %>%
  arrange(gene_name)
```

```{r noisy_sim_vs_real_counts}
noisy_sim_and_real_counts <- thirty_degree_total_rna_count %>%
  mutate(frac = "total") %>%
  sample_n(num_gene) %>%
  bind_rows(thirty_degree_sup_rna_count %>%
               mutate(frac = "sup") %>%
              sample_n(num_gene)) %>%
  bind_rows(thirty_degree_pel_rna_count %>%
               mutate(frac = "pel") %>%
              sample_n(num_gene)) %>%
  bind_rows(total_sup_pel_simulated_noisy_counts %>%
                     filter(rep == 1) %>%
                     transmute(gene_name = as.character(gene_name),
                               count = total,
                               src = "sim",
                               frac = "total")) %>%
  bind_rows(total_sup_pel_simulated_noisy_counts %>%
                     filter(rep == 1) %>%
                     transmute(gene_name = as.character(gene_name),
                               count = sup,
                               src = "sim",
                               frac = "sup")) %>%
  bind_rows(total_sup_pel_simulated_noisy_counts %>%
                     filter(rep == 1) %>%
                     transmute(gene_name = as.character(gene_name),
                               count = pel,
                               src = "sim",
                               frac = "pel"))

ggplot(noisy_sim_and_real_counts) +
  geom_histogram(aes(x = log(count),
                   fill = src),
               alpha = 0.7,
               bins = 60,
               position = "identity") +
  theme_light() +
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "ln(RNA count)", y = "", title = "Simulated vs Experimental RNA counts") +
  facet_grid(frac~1)

```

```{r skewed-simulated-frac-counts}
set.seed(338)

sup_pel_simulated_fractions_skewed <- tibble(gene_name = 1:num_gene,
                                             sup_frac = c(rep(0.75,num_gene - 20),
                                                              rep(0.25,20)),
                                                 pel_frac = 1 - sup_frac)

total_sup_pel_simulated_mean_counts_skew <- tibble(gene_name = 1:num_gene,
                                              total = rlnorm(length(gene_name),
                                                  meanlog = total_count_model$estimate[1], 
                                                  sdlog = total_count_model$estimate[2]),
                                              sup = total * sup_pel_simulated_fractions_skewed$sup_frac,
                                              pel = total * sup_pel_simulated_fractions_skewed$pel_frac)

total_sup_pel_simulated_noisy_counts_skew <- total_sup_pel_simulated_mean_counts_skew %>%
  pivot_longer(c("total", "sup", "pel"),
               names_to = "fraction",
               values_to = "perfect_counts") %>%
  inner_join(tot_sup_pel_scale_factor %>%
               pivot_longer(c("total", "sup", "pel"),
                            names_to = "fraction",
                            values_to = "scale_factor")) %>%
  group_by(fraction, rep) %>%
  summarise(gene_name = gene_name, noisy_counts = sample_noisy_counts(perfect_counts, phi, scale_factor)) %>%
  pivot_wider(names_from = "fraction", values_from = "noisy_counts") %>%
  mutate(total = as.integer(total),
         sup = as.integer(sup),
         pel = as.integer(pel)) %>%
  arrange(gene_name)
```

```{r skewed-three-condition-simulated-frac-counts}
set.seed(338)

sup_pel_simulated_fractions_skewed_multi_condition <- tibble(gene_name = rep(1:num_gene,
                                                                             num_condition),
                                                             condition = rep(1:num_condition,
                                                                             each = num_gene),
                                                             sup_frac = c(rbeta(num_gene,2,2),
                                                                          rbeta(num_gene,4,2),
                                                                          rbeta(num_gene,4,1)),
                                                             pel_frac = 1 - sup_frac)

tot_sup_pel_scale_factor_multi_condition <- tibble(rep = rep(1:num_rep,
                                                             num_condition),
                                                   condition = rep(1:num_condition,
                                                                   each = num_rep),
                                                   total = runif(num_rep * num_condition,
                                                                 min = 0.5, max = 3),
                                                   sup = runif(num_rep * num_condition,
                                                               min = 0.5, max = 3),
                                                   pel = runif(num_rep * num_condition,
                                                               min = 0.5, max = 3))

total_sup_pel_simulated_mean_counts_skewed_multi_condition <- sup_pel_simulated_fractions_skewed_multi_condition %>%
  mutate(total = rep(rlnorm(num_gene,
                            meanlog = total_count_model$estimate[1],
                            sdlog = total_count_model$estimate[2]),
                     num_condition),
         sup = total * sup_frac,
         pel = total * pel_frac)

total_sup_pel_simulated_noisy_counts_skewed_multi_condition <- total_sup_pel_simulated_mean_counts_skewed_multi_condition %>%
  dplyr::select(-sup_frac, -pel_frac) %>%
  pivot_longer(c("total", "sup", "pel"), names_to = "fraction", values_to = "perfect_counts") %>%
  inner_join(tot_sup_pel_scale_factor_multi_condition%>%
  pivot_longer(c("total", "sup", "pel"), names_to = "fraction", values_to = "scale_factor")) %>%
  group_by(fraction, condition, rep) %>%
  summarise(gene_name = gene_name, noisy_counts = sample_noisy_counts(perfect_counts, phi, scale_factor)) %>%
  pivot_wider(names_from = "fraction", values_from = "noisy_counts") %>%
  mutate(total = as.integer(total),
         sup = as.integer(sup),
         pel = as.integer(pel)) %>%
  arrange(gene_name)

```

```{r output-sim-counts}
write_tsv(total_sup_pel_simulated_noisy_counts, here("data/output/simulated_counts/total_sup_pel_simulated_noisy_counts.tsv"))

write_tsv(total_sup_pel_simulated_mean_counts, here("data/output/simulated_counts/total_sup_pel_simulated_noiseless_counts.tsv"))

write_tsv(total_sup_pel_simulated_noisy_counts_skew, here("data/output/simulated_counts/total_sup_pel_simulated_noisy_skewed_counts.tsv"))

write_tsv(total_sup_pel_simulated_noisy_counts_skewed_multi_condition, here("data/output/simulated_counts/total_sup_pel_simulated_noisy_skewed_multi_condition_counts.tsv"))
```
